/*
 * Created on 21 janv. 2015 ( Time 17:25:52 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.basics.entities;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

@Entity
@Table(name="DEPARTMENT" )

@SqlResultSetMapping (
		name = "ProfNameAndDeptName",
		columns = { 
				// Permet de changer l'ordre des colonnes ou mapper un sous-ensemble des colonnes 
				@ColumnResult(name = "PROF_NAME"),
				//@ColumnResult(name = "PROF_ID"), 
			    @ColumnResult(name = "DEP_NAME") 
		}
	)

public class DepartmentEntity {
	
  @Id
  @Column(name="ID")
  //@GeneratedValue(strategy = GenerationType.IDENTITY)
  private int id;

  @Column(name="NAME", length=50)
  private String name;

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String deptName) {
    this.name = deptName;
  }

  public String toString() {
    return "Department : id: " + getId() + ", name: " + getName();
  }
}

